apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email: ${EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef: 
      name: lets-encrypt-private-key
    solvers:
    - dns01:
        azureDNS:
          subscriptionID: ${SUBSCRIPTION_ID}
          resourceGroupName: ${DNS_ZONE_RESOURCE_GROUP}
          hostedZoneName: ${DNS_ZONE_NAME}
          managedIdentity:
            clientID: ${MANAGED_IDENTITY_CLIENT_ID}