apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-appset
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: cluster
    repoURL: https://github.com/andersonfcz/TCC---GitOps-Uma-abordagem-DevOps-para-ambientes-Cloud-Native-ageis-e-eficientes.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true