interval: 5m
sources:
  - service
  - ingress
policy: upsert-only
registry: txt
txtOwnerId: "external-dns"
provider: azure
azure:
  cloud: AzurePublicCloud
  resourceGroup: ${RESOURCE_GROUP}
  tenantId: ${TENANT_ID}
  subscriptionId: ${SUBSCRIPTION_ID}
  useManagedIdentityExtension: true